export const abi = [
  {
    type: "function",
    name: "createERC20",
    inputs: [
      { name: "name", type: "string", internalType: "string" },
      { name: "symbol", type: "string", internalType: "string" },
      { name: "maxSupply", type: "uint256", internalType: "uint256" },
      { name: "tokenPrice", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      {
        name: "token",
        type: "address",
        internalType: "contract ERC20Toqen",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createERC721",
    inputs: [
      { name: "name", type: "string", internalType: "string" },
      { name: "symbol", type: "string", internalType: "string" },
      { name: "maxSupply", type: "uint256", internalType: "uint256" },
      { name: "tokenPrice", type: "uint256", internalType: "uint256" },
      { name: "baseURI", type: "string", internalType: "string" },
    ],
    outputs: [
      {
        name: "token",
        type: "address",
        internalType: "contract ERC721Toqen",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "TokenCreated",
    inputs: [
      {
        name: "tokenAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
];

export const generate = (): { name: string; symbol: string } => {
  const firstWords = [
    "Fluffy",
    "Sparkly",
    "Sneaky",
    "Brave",
    "Jolly",
    "Grumpy",
    "Wobbly",
    "Cheeky",
    "Quirky",
    "Zany",
    "Dizzy",
    "Cranky",
    "Loony",
    "Gloomy",
    "Frosty",
    "Snappy",
    "Bouncy",
    "Squishy",
    "Muddy",
    "Greedy",
    "Giggly",
    "Slippy",
    "Sloppy",
    "Crunchy",
    "Gloopy",
    "Frizzy",
    "Slinky",
    "Spooky",
    "Kooky",
    "Loopy",
    "Dopey",
    "Sneezy",
    "Splashy",
    "Dusty",
    "Rusty",
    "Misty",
    "Cloudy",
    "Stormy",
    "Windy",
    "Sunny",
    "Hairy",
    "Baldy",
    "Sleepy",
    "Breezy",
    "Smelly",
    "Puffy",
    "Chubby",
    "Skinny",
    "Fizzy",
    "Silly",
    "Witty",
    "Lazy",
    "Crazy",
    "Snazzy",
    "Dashing",
    "Cheesy",
    "Meaty",
    "Spicy",
    "Sweet",
    "Salty",
    "Tangy",
    "Soggy",
    "Ripe",
    "Raw",
    "Zippy",
    "Zoomy",
    "Fuzzy",
    "Sticky",
    "Prickly",
    "Smooth",
    "Rough",
    "Tough",
    "Soft",
    "Hard",
    "Hot",
    "Cold",
    "Warm",
    "Cool",
    "Magical",
    "Mystic",
    "Electric",
    "Galactic",
    "Solar",
    "Lunar",
    "Radiant",
    "Shiny",
    "Dull",
    "Clear",
    "Dark",
    "Light",
    "Heavy",
    "Tiny",
    "Giant",
    "Invisible",
    "Visible",
    "Quick",
    "Slow",
    "Fast",
    "Sharp",
    "Blunt",
  ];

  const secondWords = [
    "Unicorn",
    "Goblin",
    "Mermaid",
    "Wizard",
    "Dragon",
    "Troll",
    "Chipmunk",
    "Penguin",
    "Yeti",
    "Kangaroo",
    "Sasquatch",
    "Dinosaur",
    "Pirate",
    "Ninja",
    "Robot",
    "Alien",
    "Monster",
    "Zombie",
    "Ghost",
    "Vampire",
    "Werewolf",
    "Sphinx",
    "Kraken",
    "Elf",
    "Dwarf",
    "Fairy",
    "Ogre",
    "Griffin",
    "Centaur",
    "Cyclops",
    "Minotaur",
    "Hydra",
    "Basilisk",
    "Pegasus",
    "Chimera",
    "Leprechaun",
    "Banshee",
    "Gnome",
    "Salamander",
    "Phoenix",
    "Djinn",
    "Angel",
    "Demon",
    "Poltergeist",
    "Satyr",
    "Nymph",
    "Dryad",
    "Harpy",
    "Manticore",
    "Mothman",
    "Bigfoot",
    "Loch Ness Monster",
    "Jackalope",
    "Chupacabra",
    "Yeti",
    "Mothman",
    "Mummy",
    "Cerberus",
    "Golem",
    "Leviathan",
    "Titan",
    "Medusa",
    "Valkyrie",
    "Hippogriff",
    "Siren",
    "Merlion",
    "Imp",
    "Bogle",
    "Sprite",
    "Kobold",
    "Brownie",
    "Troll",
    "Bogeyman",
    "Ghoul",
    "Wraith",
    "Specter",
    "Genie",
    "Elf",
    "Pixie",
    "Ghast",
    "Revenant",
    "Seraph",
    "Archangel",
    "Behemoth",
    "Serpent",
    "Dragon",
    "Wyvern",
    "Cockatrice",
    "Griffin",
    "Manticore",
    "Homunculus",
    "Fomorian",
    "Elemental",
    "Fae",
    "Succubus",
    "Incubus",
    "Harpy",
    "Centaur",
    "Goblin",
    "Ogre",
  ];

  const lastWords = [
    "Whisperer",
    "Enchanter",
    "Sniffer",
    "Tickler",
    "Muncher",
    "Explorer",
    "Collector",
    "Juggler",
    "Dancer",
    "Singer",
    "Rider",
    "Fighter",
    "Sleeper",
    "Dreamer",
    "Schemer",
    "Baker",
    "Painter",
    "Gardener",
    "Watcher",
    "Listener",
    "Whisperer",
    "Shouter",
    "Runner",
    "Jumper",
    "Builder",
    "Creator",
    "Destroyer",
    "Bender",
    "Shaper",
    "Maker",
    "Finder",
    "Loser",
    "Mender",
    "Breaker",
    "Raiser",
    "Lowerer",
    "Filler",
    "Emptier",
    "Opener",
    "Closer",
    "Brightener",
    "Fader",
    "Sharpener",
    "Blunter",
    "Thickener",
    "Thinner",
    "Sweetener",
    "Sourer",
    "Warmer",
    "Cooler",
    "Dryer",
    "Wetter",
    "Calmer",
    "Agitator",
    "Leader",
    "Follower",
    "Pusher",
    "Puller",
    "Lifter",
    "Dropper",
    "Shifter",
    "Switcher",
    "Changer",
    "Swapper",
    "Giver",
    "Taker",
    "Saver",
    "Spender",
    "Quietener",
    "Loudener",
    "Quickener",
    "Slower",
    "Beginner",
    "Finisher",
    "Increaser",
    "Decreaser",
    "Maximizer",
    "Minimizer",
    "Doubler",
    "Halver",
    "Multiplier",
    "Divider",
    "Combiner",
    "Separator",
    "Mixer",
    "Sorter",
    "Sifter",
    "Polisher",
    "Smudger",
    "Cleaner",
    "Stainer",
    "Filler",
    "Drainer",
    "Charger",
    "Discharger",
    "Healer",
    "Injurer",
    "Igniter",
    "Extinguisher",
    "Amplifier",
  ];

  const first = firstWords[Math.floor(Math.random() * firstWords.length)];
  const second = secondWords[Math.floor(Math.random() * secondWords.length)];
  const last = lastWords[Math.floor(Math.random() * lastWords.length)];

  const name = `${first} ${second} ${last}`;

  const symbol = `${first[0]}${second[0]}${last[0]}`;

  return { name, symbol };
};
